#########################
## zTags made by Zowpy ##
#########################

mongodb:
  use-uri: false
  uri: ""
  host: "127.0.0.1"
  port: 27017
  database: "ztag"
  authentication:
    enabled: false
    username: ""
    password: ""
    database: "admin"


# supports placeholders
# NOTE: PLACEHOLDERS ONLY WORK IF THEY EXIST.
chat-format: "<tag> <player>&f: <message>"