package me.zowpy.ztags.utils.menu;

import me.zowpy.ztags.utils.Color;
import org.bukkit.ChatColor;

public final class CC {
    public static final String PRIMARY;
    public static final String SECONDARY;
    public static final String B_PRIMARY;
    public static final String B_SECONDARY;
    public static final String BLUE;
    public static final String AQUA;
    public static final String YELLOW;
    public static final String RED;
    public static final String GRAY;
    public static final String GOLD;
    public static final String GREEN;
    public static final String WHITE;
    public static final String BLACK;
    public static final String BOLD;
    public static final String ITALIC;
    public static final String STRIKE_THROUGH;
    public static final String RESET;
    public static final String MAGIC;
    public static final String OBFUSCATED;
    public static final String B;
    public static final String M;
    public static final String O;
    public static final String I;
    public static final String S;
    public static final String R;
    public static final String DARK_BLUE;
    public static final String DARK_AQUA;
    public static final String DARK_GRAY;
    public static final String DARK_GREEN;
    public static final String DARK_PURPLE;
    public static final String DARK_RED;
    public static final String D_BLUE;
    public static final String D_AQUA;
    public static final String D_GRAY;
    public static final String D_GREEN;
    public static final String D_PURPLE;
    public static final String D_RED;
    public static final String LIGHT_PURPLE;
    public static final String L_PURPLE;
    public static final String PINK;
    public static final String B_BLUE;
    public static final String B_AQUA;
    public static final String B_YELLOW;
    public static final String B_RED;
    public static final String B_GRAY;
    public static final String B_GOLD;
    public static final String B_GREEN;
    public static final String B_WHITE;
    public static final String B_BLACK;
    public static final String BD_BLUE;
    public static final String BD_AQUA;
    public static final String BD_GRAY;
    public static final String BD_GREEN;
    public static final String BD_PURPLE;
    public static final String BD_RED;
    public static final String BL_PURPLE;
    public static final String I_BLUE;
    public static final String I_AQUA;
    public static final String I_YELLOW;
    public static final String I_RED;
    public static final String I_GRAY;
    public static final String I_GOLD;
    public static final String I_GREEN;
    public static final String I_WHITE;
    public static final String I_BLACK;
    public static final String ID_RED;
    public static final String ID_BLUE;
    public static final String ID_AQUA;
    public static final String ID_GRAY;
    public static final String ID_GREEN;
    public static final String ID_PURPLE;
    public static final String IL_PURPLE;
    public static final String VAPE = "§8 §8 §1 §3 §3 §7 §8 §r";
    public static final String BLANK_LINE = "§8 §8 §1 §3 §3 §7 §8 §r";
    public static final String BL = "§8 §8 §1 §3 §3 §7 §8 §r";

    static {
        PRIMARY = Color.translate("&c");
        SECONDARY = Color.translate("&4");
        B_PRIMARY = PRIMARY + ChatColor.BOLD;
        B_SECONDARY = SECONDARY + ChatColor.BOLD;
        BLUE = ChatColor.BLUE.toString();
        AQUA = ChatColor.AQUA.toString();
        YELLOW = ChatColor.YELLOW.toString();
        RED = ChatColor.RED.toString();
        GRAY = ChatColor.GRAY.toString();
        GOLD = ChatColor.GOLD.toString();
        GREEN = ChatColor.GREEN.toString();
        WHITE = ChatColor.WHITE.toString();
        BLACK = ChatColor.BLACK.toString();
        BOLD = ChatColor.BOLD.toString();
        ITALIC = ChatColor.ITALIC.toString();
        STRIKE_THROUGH = ChatColor.STRIKETHROUGH.toString();
        RESET = ChatColor.RESET.toString();
        MAGIC = ChatColor.MAGIC.toString();
        OBFUSCATED = MAGIC;
        B = BOLD;
        M = MAGIC;
        O = MAGIC;
        I = ITALIC;
        S = STRIKE_THROUGH;
        R = RESET;
        DARK_BLUE = ChatColor.DARK_BLUE.toString();
        DARK_AQUA = ChatColor.DARK_AQUA.toString();
        DARK_GRAY = ChatColor.DARK_GRAY.toString();
        DARK_GREEN = ChatColor.DARK_GREEN.toString();
        DARK_PURPLE = ChatColor.DARK_PURPLE.toString();
        DARK_RED = ChatColor.DARK_RED.toString();
        D_BLUE = DARK_BLUE;
        D_AQUA = DARK_AQUA;
        D_GRAY = DARK_GRAY;
        D_GREEN = DARK_GREEN;
        D_PURPLE = DARK_PURPLE;
        D_RED = DARK_RED;
        LIGHT_PURPLE = ChatColor.LIGHT_PURPLE.toString();
        L_PURPLE = LIGHT_PURPLE;
        PINK = L_PURPLE;
        B_BLUE = BLUE + B;
        B_AQUA = AQUA + B;
        B_YELLOW = YELLOW + B;
        B_RED = RED + B;
        B_GRAY = GRAY + B;
        B_GOLD = GOLD + B;
        B_GREEN = GREEN + B;
        B_WHITE = WHITE + B;
        B_BLACK = BLACK + B;
        BD_BLUE = D_BLUE + B;
        BD_AQUA = D_AQUA + B;
        BD_GRAY = D_GRAY + B;
        BD_GREEN = D_GREEN + B;
        BD_PURPLE = D_PURPLE + B;
        BD_RED = D_RED + B;
        BL_PURPLE = L_PURPLE + B;
        I_BLUE = BLUE + I;
        I_AQUA = AQUA + I;
        I_YELLOW = YELLOW + I;
        I_RED = RED + I;
        I_GRAY = GRAY + I;
        I_GOLD = GOLD + I;
        I_GREEN = GREEN + I;
        I_WHITE = WHITE + I;
        I_BLACK = BLACK + I;
        ID_RED = D_RED + I;
        ID_BLUE = D_BLUE + I;
        ID_AQUA = D_AQUA + I;
        ID_GRAY = D_GRAY + I;
        ID_GREEN = D_GREEN + I;
        ID_PURPLE = D_PURPLE + I;
        IL_PURPLE = L_PURPLE + I;
    }
}

